name: Build and Push Container Image, Helm chart

on:
  push:
    tags:
      - 'v*'
    
permissions:
  packages: write
  contents: read

jobs:
  release:
    name: Build and release.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: extract version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_ENV"

      - name: fetch
        run: |
          curl -o- -L --no-progress-meter --silent "https://github.com/devfile/devworkspace-operator/archive/refs/tags/v${{ env.VERSION }}.tar.gz" | tar xzf -
          mv "devworkspace-operator-${{ env.VERSION }}"/deploy/deployment/kubernetes/objects/* templates/
          mkdir crds/
          mv templates/*.CustomResourceDefinition.yaml crds/
          rm -r "devworkspace-operator-${{ env.VERSION }}"

      - name: filter
        run: |
          for i in templates/*.yaml; do
            yq -i 'del(.metadata.namespace)' "$i"
            yq -i '.metadata.name = ("{{ include \"..fullname\" . }}-" + .metadata.name)' "$i"
          done
          yq -i '.spec.template.spec.containers[].env[] |= select(.name == "RELATED_IMAGE_devworkspace_webhook_server").value = "{{ .Values.devworkspaceController.image.repository }}:{{ .Values.devworkspaceController.image.tag | default .Chart.AppVersion }}"' templates/devworkspace-controller-manager.Deployment.yaml
          yq -i '.spec.template.spec.containers[] |= select(.name == "devworkspaceController").imagePullPolicy = "{{ .Values.devworkspaceController.image.pullPolicy }}"' templates/devworkspace-controller-manager.Deployment.yaml
          yq -i '.spec.template.spec.containers[].env[] |= select(.name == "RELATED_IMAGE_project_clone").value = "{{ .Values.projectClone.image.repository }}:{{ .Values.projectClone.image.tag | default .Chart.AppVersion }}"' templates/devworkspace-controller-manager.Deployment.yaml
          yq -i '.spec.template.spec.serviceAccountName = "{{ include \"..fullname\" . -}} -devworkspace-controller-serviceaccount"' templates/devworkspace-controller-manager.Deployment.yaml

          yq -i '.spec.dnsNames = [ "{{ include \"..fullname\" . -}} -devworkspace-webhookserver. {{- .Release.Namespace -}} .svc", "{{ include \"..fullname\" . -}} -devworkspace-webhookserver. {{- .Release.Namespace -}} .svc.cluster.local", "{{ include \"..fullname\" . -}} -devworkspace-controller-manager-service. {{- .Release.Namespace -}} .svc", "{{ include \"..fullname\" . -}} -devworkspace-controller-manager-service. {{- .Release.Namespace -}} .svc.cluster.local" ]' templates/devworkspace-controller-serving-cert.Certificate.yaml
          yq -i '.spec.issuerRef.name = "{{ .Release.Name -}} -devworkspace-controller-selfsigned-issuer"' templates/devworkspace-controller-serving-cert.Certificate.yaml

          yq -i '.subjects[] |= select(.kind == "ServiceAccount") = { "kind": .kind, "name": "{{ include \"..fullname\" . }}-" + .name, "namespace": "{{ .Release.Namespace }}" }' templates/devworkspace-controller-leader-election-rolebinding.RoleBinding.yaml

          yq -i '.subjects[] |= select(.kind == "ServiceAccount") = { "kind": .kind, "name": "{{ include \"..fullname\" . }}-" + .name, "namespace": "{{ .Release.Namespace }}" }' templates/devworkspace-controller-proxy-rolebinding.ClusterRoleBinding.yaml

          yq -i '.subjects[] |= select(.kind == "ServiceAccount") = { "kind": .kind, "name": "{{ include \"..fullname\" . }}-" + .name, "namespace": "{{ .Release.Namespace }}" }' templates/devworkspace-controller-rolebinding.ClusterRoleBinding.yaml

      - name: setup helm
        uses: azure/setup-helm@v4

      - name: lint
        run: helm lint

      - name: package
        run: helm package "--app-version=${{ env.VERSION }}" "--version=${{ env.VERSION }}" .

      - name: login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login "ghcr.io/${{ github.repository_owner }}" --username "${{ github.repository_owner }}" --password-stdin
      
      - name: Push the chart
        run: helm push "./devworkspace-operator-${{ env.VERSION }}.tgz" "oci://ghcr.io/${{ github.repository_owner }}"
